In [1]:
import pandas as pd
import numpy as np
import time
import iddModel.learnUsingNumpy as idoctor
import multiprocessing
import parmap 
pd.set_option('display.max_row', 1200)
pd.set_option('display.max_columns', 100)

In [2]:
tuningSetAgeRate = [[0.1, 0.2, 0.9],[26,28,27],[40,40,40]]
tuningSetRetireRate = [1.4,35,0.2]
%time npCostData = idoctor.getCost([tuningSetAgeRate, tuningSetRetireRate])
pd.DataFrame(npCostData)

CPU times: user 14.5 ms, sys: 14.2 ms, total: 28.8 ms
Wall time: 22 ms

,0,1,2,3,4,5,6,7,8,9,10,11
0,9418,7496,7192,158,4060,1368,0.0233792,0.0756676,0.0462088,0.0397671,0.0729549,0.0325335
1,5614,4018,521,35,425,1535,0.0233792,0.0406015,0.0109752,0.0107433,0.00915858,0.0136547
2,9503,6008,6718,37,2715,471,0.0240397,0.0573803,0.0384127,0.0404125,0.0572331,0.022187
3,5861,3130,1027,174,151,1681,0.0240397,0.0300724,0.00643247,0.00824714,0.00615157,0.0147985
4,8552,4448,5359,298,1408,451,0.0216337,0.0396751,0.0253656,0.0371585,0.0393722,0.0101437
5,5480,2282,828,285,238,1847,0.0216337,0.0203801,0.00769297,0.00576102,0.00164442,0.016352
6,8634,3174,4666,357,275,1426,0.0229512,0.0251427,0.0169478,0.0369848,0.0276788,0.000378146
7,5841,1636,1091,479,609,2026,0.0229512,0.0127482,0.00563315,0.0037553,0.00191342,0.017678
8,8700,1681,4360,818,994,2483,0.0235096,0.00919986,0.0127802,0.0402312,0.0151617,0.00990313
9,6093,631,1590,651,1060,2161,0.0235096,0.00198843,0.000982141,0.00212644,0.0060674,0.0185624
10,8360,231,3303,867,2033,3660,0.0247122,0.00516575,0.00250007,0.0386531,0.00454363,0.0211502
11,6300,435,1927,983,1561,2264,0.0247122,0.00876926,0.00242782,0.00128052,0.010629,0.0191442

In [7]:
def runGetCost(tuningValueList):
    resultData = []
    
    for value in tuningValueList:
        resultData.append([value ,idoctor.getCost([[[value[0], value[1], value[2]],[26,28,27],[40,40,40]], [value[3],30,value[4]]])])
        
        
    return resultData

In [11]:
def startGetCost():
    tAge1 = np.arange(0.4, 1, 0.1) # 연령분포모델1 변수 / 범위 0~1
    tAge2 = np.arange(0.4, 1, 0.1) # 연령분포모델2 변수 / 범위 0~1
    tAge3 = np.arange(0.4, 1, 0.1) # 연령분포모델3 변수 / 범위 0~1
    tRetire1 = np.arange(1.01, 1.2, 0.01) # 은퇴율모델 변수1 / 범위 1 이상
    tRetire2 = np.arange(1, 3, 0.1) # 은퇴율모델 변수3 / 범위 0~1
    
    dataSize = len(tAge1)*len(tAge2)*len(tAge3)*len(tRetire1)*len(tRetire2)
    timeMinute = dataSize*20/1000/60
    curentData = 0
    resultData = []
    
    num_cores = 30

    now = time.localtime()
    print("│ Start Time : %04d/%02d/%02d %02d:%02d:%02d" % (now.tm_year, now.tm_mon, now.tm_mday, now.tm_hour+9, now.tm_min, now.tm_sec))
    print("│ expect running time : " + str(round(timeMinute)) + "min")
    print("│ Data Size = " + str(dataSize))
    print("└───────────────────────")
    print('│ '+str(round(curentData/dataSize*100,2))+'%')
    
    tuningList = []
    
    for i in tAge1:
        for j in tAge2:
            for k in tAge3:
                for m in tRetire1:
                    for n in tRetire2:
                        tuningList.append([i,j,k,m,n])

    
    splitedTuningList = np.array_split(tuningList, num_cores) 
    splitedTuningList = [i.tolist() for i in splitedTuningList] 
    
    result = parmap.map(runGetCost, splitedTuningList, pm_pbar=True, pm_processes=num_cores)
    
    print("| End Time : %04d/%02d/%02d %02d:%02d:%02d" % (now.tm_year, now.tm_mon, now.tm_mday, now.tm_hour+9, now.tm_min, now.tm_sec))
    return result

In [12]:
%time liCostData = startGetCost()

│ Start Time : 2020/11/09 22:19:11
│ expect running time : 27min
│ Data Size = 82080
└───────────────────────
│ 0.0%

100%|██████████| 30/30 [01:16<00:00,  2.57s/it]

| End Time : 2020/11/09 22:19:11
CPU times: user 2.12 s, sys: 748 ms, total: 2.86 s
Wall time: 1min 17s

In [15]:
npCostData = np.array(liCostData)

list

In [9]:
value = [0.4, 0.8, 0.4, 40, 1.09, 30, 1.9]

data = idoctor.getCost([[[value[0], value[1], value[2]],[26,28,27],[value[3],value[3],value[3]]], [value[4],value[5],value[6]]])
data

array([[1744.0, 6267.0, 7775.0, 1576.0, 6898.0, 7312.0,
        0.02953430761875242, 0.07487325041308313, 0.0909988023070972,
        0.02184636564799869, 0.08477076985133991, 0.0887892248395942],
       [2676.0, 3189.0, 1174.0, 444.0, 888.0, 355.0,
        0.029534307618752448, 0.03810070283710047, 0.012858672327869067,
        0.006062386771428126, 0.0109683118075878, 0.004394368967201155],
       [2361.0, 4941.0, 7148.0, 1738.0, 5861.0, 6851.0,
        0.031139553338381143, 0.05774434249250604, 0.08279851968049609,
        0.021522431490391486, 0.06947584344827032, 0.08068414057272144],
       [2748.0, 2354.0, 1605.0, 261.0, 641.0, 309.0,
        0.031139553338381115, 0.027512739716174264, 0.01828759356073896,
        0.003349486785524644, 0.007638184575442426,
        0.0036731085775650353],
       [4061.0, 3352.0, 5839.0, 1963.0, 4918.0, 6371.0,
        0.03000405275404472, 0.03906208263282336, 0.07131033033553993,
        0.01710045792039197, 0.052404702242285134, 0.07087130555973081],
       [2175.0, 1434.0, 1455.0, 137.0, 334.0, 243.0, 0.03000405275404469,
        0.016754605285113175, 0.01921416809345783,
        0.00021774534899277748, 0.0032076060524681878,
        0.002539369223065373],
       [4764.0, 1916.0, 5252.0, 1975.0, 4083.0, 5874.0,
        0.0327121230087678, 0.02256585061813457, 0.0646183250136397,
        0.01552020416378172, 0.04097740203109643, 0.06339869244566396],
       [2329.0, 642.0, 1775.0, 126.0, 32.0, 182.0, 0.03271212300876783,
        0.007780297878231143, 0.02319309469651329, 0.0030793923785594063,
        0.0004104597346858488, 0.001751121679221859],
       [5522.0, 367.0, 4798.0, 2144.0, 3223.0, 5320.0,
        0.03453994669437488, 0.005682847839373256, 0.06015852759436707,
        0.015369206487223286, 0.029449363367189868, 0.05556275227370201],
       [2362.0, 349.0, 2178.0, 380.0, 298.0, 145.0, 0.03453994669437485,
        0.002880747456528124, 0.02812501232257969, 0.006291202170666622,
        0.004252415312311297, 0.0012479356546546676],
       [6730.0, 988.0, 3551.0, 2012.0, 2529.0, 4752.0,
        0.03710998400133603, 0.00814213988637666, 0.048557756273298364,
        0.010771008013241684, 0.019276603762360373, 0.0474779886126557],
       [2340.0, 1339.0, 2333.0, 833.0, 634.0, 121.0,
        0.037109984001336055, 0.01283579529621021, 0.030825419691095132,
        0.011818948706023867, 0.00815619005753978, 0.0008547791571125122]],
      dtype=object)

In [89]:
len(liCostData)

30

In [78]:
minCost = [[1000000,1000000,[]],[1000000,1000000,[]]]

for i in range(263169):
    
    npManCost = (np.concatenate((liCostData[i][1][0],liCostData[i][1][2],liCostData[i][1][4],liCostData[i][1][6],liCostData[i][1][8],liCostData[i][1][10])))
    npWomanCost = (np.concatenate((liCostData[i][1][1],liCostData[i][1][3],liCostData[i][1][5],liCostData[i][1][7],liCostData[i][1][9],liCostData[i][1][11])))
    
    npManCost = npManCost.reshape(6,12).sum(axis=0)
    npWomanCost = npWomanCost.reshape(6,12).sum(axis=0)

#    npManCost = npManCost.reshape(6,12)[5]
#    npWomanCost = npWomanCost.reshape(6,12)[5]
    
    totalManCost = npManCost[1]
    totalManRateCost = npManCost[6]
    
    totalWomanCost = npWomanCost[0]
    totalWomanRateCost = npWomanCost[6]
    
    if minCost[0][0]>=totalManCost:
        if minCost[0][1]>=totalManRateCost:
            minCost[0][0] = totalManCost
            minCost[0][1] = totalManRateCost
            minCost[0][2] = np.round(liCostData[i][0],4)

    if minCost[1][0]>=totalWomanCost:
        if minCost[1][1]>=totalWomanRateCost:
            minCost[1][0] = totalWomanCost
            minCost[1][1] = totalWomanRateCost
            minCost[1][2] = np.round(liCostData[i][0],4)

            
            
pd.DataFrame(minCost)

         0         1                                       2
0  21502.0  0.138926  [0.1, 0.8, 0.6, 40.0, 1.19, 30.0, 1.9]
1  14630.0  0.195040  [0.4, 0.8, 0.4, 40.0, 1.09, 30.0, 1.9]